In [1]:
import numpy as np

In [4]:
arr=np.array([4,5,8,2,9])
arr

array([4, 5, 8, 2, 9])

In [5]:
arr.ndim  #(ndim) used to check the dimensional of aaray

1

In [30]:
arr=np.array([[4,5,8,2,9]])
arr

array([[4, 5, 8, 2, 9]])

In [7]:
arr.ndim

2

# ndmin

it is used to convert the array dinmension from 1D to 2D and 3D 

In [74]:
ar=([10,50,14,86])
ar

[10, 50, 14, 86]

In [75]:
ar=np.array([10,50,14,86],ndmin=2)
ar

array([[10, 50, 14, 86]])

In [5]:
ar=np.array([[4,5,8,9],[3,7,6,2,1]])
ar

<ipython-input-5-307db2830d5e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar=np.array([[4,5,8,9],[3,7,6,2,1]])


array([list([4, 5, 8, 9]), list([3, 7, 6, 2, 1])], dtype=object)

In [9]:
a.ndim  # if values will be eqaul in both list then it will 2D array else 1D

1

# 3 Dimenstional

In [6]:
ar=np.array([[[4,6,2],[3,5,8],[8,3,7]]])
ar

array([[[4, 6, 2],
        [3, 5, 8],
        [8, 3, 7]]])

In [4]:
ar.sum(axis=1) #axis=1 used to add row wise data in 3D

array([[15, 14, 17]])

In [5]:
ar.sum(axis=2)  #axis=2 used to add colunm wise data in 3D

array([[12, 16, 18]])

# 2 Dimentional

In [22]:
ar=np.array([[4,6,2],[3,5,8],[8,3,7]])
ar

array([[4, 6, 2],
       [3, 5, 8],
       [8, 3, 7]])

In [25]:
ar.sum(axis=0)  #axis=0 used to add row wise data in 2D

array([15, 14, 17])

In [24]:
ar.sum(axis=1)   #axis=1 used to add row wise data in 2D

array([12, 16, 18])

Adding two normal list

In [33]:
x=[4,2,5]
y=[3,5,8]
x+y

[4, 2, 5, 3, 5, 8]

Adding numpy array list

In [35]:
a=np.array([[5,10,4,9],[6,7,9,8]])
b=np.array([[6,8,9,11],[4,7,5,6]])
a+b

array([[11, 18, 13, 20],
       [10, 14, 14, 14]])

In [36]:
a-b  #subtract

array([[-1,  2, -5, -2],
       [ 2,  0,  4,  2]])

In [37]:
a*b #multiply

array([[30, 80, 36, 99],
       [24, 49, 45, 48]])

In [38]:
a/b # divide

array([[0.83333333, 1.25      , 0.44444444, 0.81818182],
       [1.5       , 1.        , 1.8       , 1.33333333]])

How to transpose a matrix

In [40]:
a=np.array([[5,10,4,9],[6,7,9,8]])
a

array([[ 5, 10,  4,  9],
       [ 6,  7,  9,  8]])

In [41]:
a.T #colunm to rwo

array([[ 5,  6],
       [10,  7],
       [ 4,  9],
       [ 9,  8]])

# Searching (use of where as condition)

In [6]:
z=np.array([10,45,9,11,98,102,33,58,74,100])
arr=np.where(z%2==0)

In [7]:
arr #index wise output

(array([0, 4, 5, 7, 8, 9], dtype=int64),)

In [45]:
arr=np.where(z>=58)
arr

(array([4, 5, 7, 8, 9], dtype=int64),)

In [47]:
arr=np.where(z%2!=0)
arr

(array([1, 2, 3, 6], dtype=int64),)

# Sort

In [49]:
a=np.array([10,45,9,11,98,102,33,58,74,100])
a.sort()
a

array([  9,  10,  11,  33,  45,  58,  74,  98, 100, 102])

In [51]:
arr=np.array([[100,105,245],[95,201,400],[800,700,560]])

In [52]:
arr.min()

95

In [53]:
arr.max()

800

In [54]:
arr.mean()

356.22222222222223

# arg

it works index wise

In [65]:
arr=np.array([[10,105,245],[95,201,400],[800,700,900]])
arr

array([[ 10, 105, 245],
       [ 95, 201, 400],
       [800, 700, 900]])

In [66]:
arr.argmin()

0

In [67]:
arr.argmax()

8

In [68]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [1, 0, 2]], dtype=int64)