# What is Numpy.

NumPy is a Python library used for working with arrays. and matrices.

NumPy stands for Numerical Python.

In [1]:
import numpy as np

One dimensional array in numpy. eg - ([ ])

In [ ]:
# how to take array in python

In [5]:
x=np.array([3,4,6])

In [6]:
x

array([3, 4, 6])

In [7]:
type(x)

numpy.ndarray

Two dimensional array in numpy. eg - ([[ ]])

In [8]:
x=np.array([[3,4,6]]) 

In [6]:
x

array([[3, 4, 6]])

In [7]:
x.shape

(1, 3)

In [2]:
a=np.array([[1,3,6,],[2,3,4],[2,3,5]])
a

array([[1, 3, 6],
       [2, 3, 4],
       [2, 3, 5]])

In [3]:
a.shape

(3, 3)

In [15]:
type(a)

numpy.ndarray

In [13]:
x=np.array([2,3,4,5])

In [14]:
x

array([2, 3, 4, 5])

In [4]:
type(x)

numpy.ndarray

In [16]:
x.shape

(4,)

In [4]:
a=np.array([[1,3,6,],[2,3,4],[2,3,5]])

In [5]:
a

array([[1, 3, 6],
       [2, 3, 4],
       [2, 3, 5]])

In [18]:
a.sum(axis=0)

array([ 5,  9, 15])

In [19]:
a.sum(axis=1)

array([10,  9, 10])

# array with the help of some method and attributes
1)zeros
  2)ones
     3)arrange

In [6]:
x=np.array([0,0,0])

In [7]:
x.sum(axis=0)

0

# zeros

In [27]:

x=np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [29]:
x=np.zeros((2,6))
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# onec

In [31]:

y=np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [34]:
y=np.ones((2,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
y=np.ones((6,2,5))
y

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# write a program and make an array of 3 by 7 of both zero and one.

In [37]:
y=np.zeros((3,7))
y

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [38]:
y=np.ones((3,7))
y

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

# arange

In [42]:
#it works like range function(start:end:step size)
a=np.arange(1,6,2)
a

array([1, 3, 5])

In [43]:
a=np.arange(10,100,8)
a

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90, 98])

# cheatsheet

In [ ]:
# cheatsheet

np.arange() # press the shift+tab in side the bracket

# Condition

In [16]:
# In numpy condition work on the 'index'


arr=np.array([5,6,9,8,10,15,40,100,54,76,45,35])
arr

array([  5,   6,   9,   8,  10,  15,  40, 100,  54,  76,  45,  35])

In [18]:
a=np.where(arr%3==0)
a

(array([ 1,  2,  5,  8, 10], dtype=int64),)

In [20]:
b=np.where(arr>15)
b

(array([ 6,  7,  8,  9, 10, 11], dtype=int64),)

# Test

In [7]:
arr=np.array([1,2,3,4,5])

In [15]:
arr.ndim

1

In [13]:
arr=np.array([1,2,3,4,5],ndmin=2)

In [14]:
    arr

array([[1, 2, 3, 4, 5]])

In [56]:
a=np.array([[[1,3,6,],[2,3,4],[2,3,5]]])
a

array([[[1, 3, 6],
        [2, 3, 4],
        [2, 3, 5]]])

In [58]:
a[0][2]

array([2, 3, 5])

In [13]:
a.ndim

3

In [12]:
x=np.array([[1,2,3,4,5],[10,5,12,50,5]])
print(x)
print(x.ndim)

[[ 1  2  3  4  5]
 [10  5 12 50  5]]
2


In [54]:
print(a[1][2])

12


In [27]:
x=np.array([2,3,4,5,6,8,9])
print(x[1:4])

[3 4 5]


In [33]:
x=np.array([2,3,4,5,6,8,9])
print(x[1:4:2])

[3 5]


In [44]:
x=np.array([2,3,4,5,6,8,9])
print(x[::2])

[2 4 6 9]


In [6]:
x=np.array([1,2,3,4])
x.ndim

1

In [8]:
a=np.array([[1,2,3,4],[4,5,6,7]])

In [9]:
a.ndim

2

In [13]:
arr=np.array([1,2,3,4,5],ndmin=3)
arr

array([[[1, 2, 3, 4, 5]]])

In [14]:
arr.ndim

3

In [20]:
x=np.array([[1,2,3,4,5],[10,5,12,50,5],[100,50,12,45,55]])

In [21]:
x

array([[  1,   2,   3,   4,   5],
       [ 10,   5,  12,  50,   5],
       [100,  50,  12,  45,  55]])

In [24]:
x[2][3]

45

In [12]:
a=np.array([[[[[[4,5,7],[8,9,6],[5,3,7]]]]]])

In [13]:
a

array([[[[[[4, 5, 7],
           [8, 9, 6],
           [5, 3, 7]]]]]])

In [14]:
a.ndim

6